require('config.configs')
require('config.keymaps')
require('config.autocmds')
require('config.lazy')
require('custom.llm_chat')
vim.lsp.enable({ 'lua_ls', 'bashls', 'basedpyright', 'gopls', 'ruff', 'yamlls' })
